# Nome da aplicacao
spring.application.name=catalogo-api

# Porta do servidor (padrao: 8080)
server.port=8080

# Habilitar Swagger UI em /swagger-ui/index.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
